### ISSUE TITLE
Dynamically added Javascript not deploying in IE

### ISSUE THREAD

**Issue by cblusilver** [iamnoah/writeCapture#10]
Hi,

I'm trying to dynamically add ads that contain some Javascript.  It works great in Firefox, Safari and Chrome but the added javascript in the snippet doesn't seem to be deploying in Internet Explorer 7 and 8.

Here's what I'm doing:

```
                     jQuery(".location").each(function() {
                                jQuery(this).replaceWith(writeCapture.sanitize(retrieved_ad));
                            });
```

Here's a sample of the value that retrieved_ad can have:

&lt;div class="advertisement"&gt;  &lt;!-- Begin: AdBrite, Generated: 2010-01-18 12:05:49 --&gt; &lt;script type="text/javascript"&gt; var AdBrite_Title_Color = '0000FF'; var AdBrite_Text_Color = '000000'; var AdBrite_Background_Color = 'FFFFFF'; var AdBrite_Border_Color = 'CCCCCC'; var AdBrite_URL_Color = '008000'; try{var AdBrite_Iframe=window.top!=window.self?2:1;var AdBrite_Referrer=document.referrer==''?document.location:document.referrer;AdBrite_Referrer=encodeURIComponent(AdBrite_Referrer);}catch(e){var AdBrite_Iframe='';var AdBrite_Referrer='';} &lt;/script&gt; &lt;script type="text/javascript"&gt;document.write(String.fromCharCode(60,83,67,82,73,80,84));document.write(' src="http://ads.adbrite.com/mb/text_group.php?sid=1439121&zs=3330305f323530&ifr='+AdBrite_Iframe+'&ref='+AdBrite_Referrer+'" type="text/javascript"&gt;');document.write(String.fromCharCode(60,47,83,67,82,73,80,84,62));&lt;/script&gt; &lt;div&gt;&lt;a href="http://foobar.com/www/delivery/ck.php?oaparams=2__bannerid=138__zoneid=21__source=bgV%3Db3RoZXI%3D%2CbtA%3DMTAwMDAwOTI%3D%2CJsR%3D941160000%2CyEr%3DCA%2CbcB%3DYWRtaW4%3D__cb=10000016:10000092:ffafed06f6__oadest=http://www.adbrite.com/mb/commerce/purchase_form.php?opid=1439121&afsid=1" style="font-weight:bold;font-family:Arial;font-size:13px;" target="_blank"&gt;Your Ad Here&lt;/a&gt;&lt;/div&gt; &lt;!-- End: AdBrite --&gt;&lt;div id='beacon_ffafed06f6' style='position: absolute; left: 0px; top: 0px; visibility: hidden;'&gt;&lt;img src='http://foobar.com/www/delivery/lg.php?bannerid=138&amp;campaignid=38&amp;zoneid=21&amp;source=bgV=b3RoZXI=,btA=MTAwMDAwOTI=,JsR=941160000,yEr=CA,bcB=YWRtaW4=&amp;loc=1&amp;referer=http%3A%2F%2Fjchung.dev.foobar.com%2Fad%2Fapi%2Fget_ad%3Fz%3D21&amp;cb=ffafed06f6' width='0' height='0' alt='' style='width: 0px; height: 0px;' /&gt;&lt;/div&gt; &lt;/div&gt;

I'm using writeCapture-1.0.0-nolib-min.js.

Is there something I'm missing?

Thanks!

**Comment by iamnoah** [comment]
Hi Lyn,

What would you put in the source of your page to generate the ad in the first place? Is it really that entire chunk? That looks like something a script would generate.

**Comment by cblusilver** [comment]
The value for retrieved_ad is what I get back from an ajax call that's executed after the page loads.

**Comment by iamnoah** [comment]
Try adding this line before your loop:

```
writeCapture.proxyGetElementById = true;
```

**Comment by cblusilver** [comment]
That didn't do it.

**Comment by iamnoah** [comment]
Hmmmm, I'll try to look closer into this. But in the meantime, can you grab the latest source and try:

```
writeCapture.writeOnGetElementById = true;
```

**Comment by mikerobinson** [comment]
Just tested .writeOnGetElementById - works like a charm!

**Comment by iamnoah** [comment]
Ah, I see the issue. Apparently any var variables declared in IE will not be turned into globals when using eval. We will have to use a script tag hack instead.

**Comment by iamnoah** [comment]
Ewww. noLib also seems to have a number of problems in IE. Need to catch it up.

**Comment by iamnoah** [comment]
Lyn,

I think I've resolved the issue. Please try the latest source. Replace writeCapture-1.0.0-nolib-min.js with http://github.com/iamnoah/writeCapture/raw/master/support/nolib-support.js and http://github.com/iamnoah/writeCapture/raw/master/writeCapture.js.

**Comment by cblusilver** [comment]
That worked!  Thank you for your help Noah!

**Comment by iamnoah** [comment]
Wonderful! I think I'll do another release in the next day to get some of these bug fixes out there. Thanks for the report!

**Comment by cblusilver** [comment]
This is a minor thing but I'm getting a an error in IE for "Expected ';'".  It looks like writeCapture.js has a few places missing a semicolon, lines 111, 648, and 660.  But this didn't seem to have fixed the error.  I'm going to keep looking but thought you might like to know about those.

**Comment by iamnoah** [comment]
Hmmm, I'll run JS Lint over the code.
