### ISSUE TITLE
Fix for wrong detection of type attribute

### ISSUE THREAD

**Issue by beest** [iamnoah/writeCapture#13]
Firstly, thanks for your efforts with this plugin - it's been really useful!

I was trying to use it with the following script tag - a Google Gadget - but there were problems when doing this dynamically (the script tag was skipped, therefore the contained document.write kicked in and the page was nuked):

```
<script src="http://www.gmodules.com/ig/ifr?url=http://digg.com/goog/ig.xml&amp;up_user=&amp;up_thumbnail=1&amp;up_filter=0&amp;up_num=5&amp;up_type=popular&amp;up_refresh=0&amp;up_tab=0&amp;up_offset=0&amp;up_pagination=0&amp;up_business=true&amp;up_entertainment=true&amp;up_gaming=true&amp;up_lifestyle=true&amp;up_offbeat=true&amp;up_politics=true&amp;up_science=true&amp;up_sports=true&amp;up_technology=true&amp;up_world_news=true&amp;synd=open&amp;w=320&amp;h=200&amp;title=Digg&amp;border=%23ffffff%7C3px%2C1px+solid+%23999999&amp;output=js"></script>
```

I investigated, and the problem was that the URL parameter "up_type=popular" was regex matched as the type attribute of the script tag. The code was therefore detecting this as non-Javascript and skipping the write capturing.

To fix this I've added a space before the attribute name in the attrPattern function:

```
return new RegExp('\\s' + name + '=(?:(["\'])([\\s\\S]*?)\\1|([^\\s>]+))','i');
```

Hope this helps!

Simon @ BaseKit

**Comment by iamnoah** [comment]
Thanks Simon, I'll patch this immediately.
