### ISSUE TITLE
document.createElement AND document.getElementById

### ISSUE THREAD

**Issue by beest** [iamnoah/writeCapture#15]
I've got a script that uses document.createElement and then applies attributes and HTML to the element. However, I think that later on it also relied on getElementById (via the proxy) to change this element. When a script works like this, could the resulting element be incorrect?

FYI - I'm testing with the Twitter Profile widget at http://twitter.com/goodies/widget_profile, and trying to insert this dynamically into a page.

Thanks for any help you can provide here!

Simon

**Comment by beest** [comment]
OK - I need to apologise again, because I hadn't noticed the writeOnGetElementById property. I've set this to true and all works OK now.

This is a kick ass library - thanks for the hard work!

Simon @ BaseKit

**Comment by iamnoah** [comment]
Glad it worked out!
