### ISSUE TITLE
Weird firefox bug with getJson

### ISSUE THREAD

**Issue by mardu** [iamnoah/writeCapture#18]
I noticed that Firefox 3.6.13 (mine is Ubuntu 10.10, but this should be a platform independent bug) has a really weird issue with writeCapture.

Compare these really easy two testcases. The first one is broke, the other one works. The only difference between them is an emty javascript file that is loaded at the end of the page. If i comment it out, it startst to work. There is really no difference if this file is empty or not. It won't work anyway.

http://f.postimees.ee/test/   (broke - content appears at the bottom)
http://f.postimees.ee/test/works.html   (works)

Other browser do not have this issue.

Using proxyGetElementById or writeOnGetElementById does not make any difference.

**Comment by iamnoah** [comment]
This is just a guess, but the problem may be that the page is still loading when your getJSON callback fires. What happens if you don't call getJSON until the page is fully loaded?

**Comment by mardu** [comment]
You guessed right. When I wrap $(document).ready into test.js, it starts to work again, but I still expect that it is a bug not a feature?

**Comment by iamnoah** [comment]
"I still expect that it is a bug not a feature?"

That depends on how hard it is to fix ;-)

Technically, writeCapture is for capturing document.write AFTER page load. During page load, a lot of weird things can happen. I would guess that FF is allowing an async callback to run while it tries to load the 2nd script, so the DOM is in an inconsistent state where it doesn't like being manipulated. I'm not sure how we would fix that without adding our own $(document).ready call.

Still, I'll look into it. If there is an easy fix, we'll do it. But there is a good workaround.

Try using doc.ready inside your callback. Then you can still preload your JSON, but the wc calls shouldn't fail.

**Comment by mardu** [comment]
Thanks,

My "real" solution is far more complicated than this example but anyway, thanks alot for the information. I will try to use doc.ready and hope it works.

**Comment by iamnoah** [comment]
Let me know if it doesn't work.

**Comment by mardu** [comment]
It works :)
