### ISSUE TITLE
Doubleclick 3rd party Flash Ads don't show up

### ISSUE THREAD

**Issue by gansbrest** [iamnoah/writeCapture#20]
I'm trying to use the plugin like this (see below), but after document ready I see white screen which constantly load something (looks like document.write was not captured or something): 

Could you please take a look at that sample when you get a sec? That ad call should work for a while.

```
var sampleCode = '<script language="JavaScript" src="http://ad.doubleclick.net/adj/mansueto.fcmba/homepage;sz=728x90;pos=top;dcove=d;tile=1;dcopt=ist;lan=en;c_type=splash;chn=homepage;cms=106a6c241b8797f52e1e77317b96a201;ord=1297708668?" type="text/javascript"></script>';

$("#ads-780x90-leaderboard").writeCapture().html(sampleCode);
```

Thanks a lot!

**Comment by iamnoah** [comment]
Have you tried the [Options](https://github.com/iamnoah/writeCapture/wiki/Options)? Specifically proxyGetElementById and writeOnGetElementById.

**Comment by gansbrest** [comment]
Hi

Just tried proxyGetElementById and writeOnGetElementById with no luck :(

When use those options I can see new element added to the target container, but no content as before:

`<div id="__document_write_ajax_div-4" style="display: none;"/>`

Thanks a lot for looking into it!

**Comment by iamnoah** [comment]
What browser? Looks fine to me in Firefox.

**Comment by gansbrest** [comment]
Firefox/3.0.1 Linux 

I use jQuery 1.3.2 and latest minified version of writeCapture (1.0.5)

Did you use any Options for your test page to make it work?

I'm going to build new page just for testing, maybe it's something else on the site interferes with the plugin.

**Comment by iamnoah** [comment]
Try the latest source. This: https://github.com/iamnoah/writeCapture/raw/master/plugin/jquery.writeCapture.js
plus this: https://github.com/iamnoah/writeCapture/raw/master/writeCapture.js

**Comment by iamnoah** [comment]
Assuming this has been resolved. Reopen if you have more info.

**Comment by gansbrest** [comment]
Looks like in my case the problem was related to jQuery adding addition argument to the ad call (&_=1298768423) to prevent caching or something and because of it 3rd party ad server was returning 400 Bad Request instead of actual ad creative. 

As per iamnoah suggestion I use nolib version of library and it works so far.

Thanks a lot!
