### ISSUE TITLE
$ shortcut should not be used in jQuery plugins

### ISSUE THREAD

**Issue by kellyjanderson** [iamnoah/writeCapture#21]
Because jQuery may be used in no conflict mode the $ shortcut may not be assigned to jQuery. in jquery.writecapture.js and writecapture.js all references to $ should be replaced with jQuery to ensure the plugin works in no conflict environments.

**Comment by iamnoah** [comment]
$ is a local variable inside a closure in writeCapture.js and in fact isn't even jQuery. It's a jQuery wrapper or an implementation of write capture support. 

The plugin should work just fine in no conflict environments. Feel free to add a test case that shows otherwise if you have one.
