### ISSUE TITLE
document.write() while writeCapture gets messed up

### ISSUE THREAD

**Issue by bpletzer** [iamnoah/writeCapture#23]
Hi noah,

we're getting really good results with your work.

On the way we have found another problem, which could be just me not understanding your code. While capturing a snippet calling a slow connection, following document.writes get messed up with the captured code: https://gist.github.com/9e0650b6340292eef810

(A way to avoid that problem is to call writeCapture not before domReady)

greetings

Benedikt

**Comment by iamnoah** [comment]
Write capture needs to be called after dom ready.
