### ISSUE TITLE
paying attention to <script> attrs

### ISSUE THREAD

**Issue by vilmibm** [iamnoah/writeCapture#24]
Howdy,

I'm having to work with some ads javascript that does this cute trick (summarized):

document.write('<script id="foo"></script><script>setTimeout('document.getElementById("foo").src="some_more_ad_stuff.js"', 1)</script>')

writeCapture, as far as I'm concerned, is not doing anything wrong here--<script> tags are not supposed to use any of the standard attributes (like id). But because the <script>s in the doc.write don't ever get added to the dom the ads break.

I'm working on a patch now to support their behavior, and thought I'd bring it up here in case there was already a good workaround for shenanigans like this.

(I can submit whatever I come up with, but understand that supporting every wicked whim of various ad vendors is not a feature of writecapture).

thanks,
Nathaniel

**Comment by iamnoah** [comment]
Wow. That's goofy. So writeCapture actually does preserve attributes, but the underlying library that executes the script tags (jQuery or the standalone support) does not. Also, they remove the tags. e.g.,

```
writeCapture.sanitize('<script id="foo">...</script>') === '<script id="foo">someWriteCaptureInternalCode();</script>'
```

So the best workaround would be to implement a replaceWith according to the support docs that leaves the tags intact. I'll add a "blessed" property (writeCapture.support) to expose the internals so you can do that. e.g.,

```
writeCapture.support.replaceWith = myReplaceWith;
```

Added support in commit a9714a6bf8020498a9aceac03aa72ae0538a8aab

**Comment by iamnoah** [comment]
By the way, please reopen if you need something else.

**Comment by vilmibm** [comment]
Thanks!

Yes, I realized after opening this that it was _jquery_ who was tossing out the <script> tag...not wC tossing out the id attr. My workaround was a hack in sanitize that added a dummy <script> tag with the desired id attr directly to the DOM with appendChild if a <script> tag with an id attr was spotted.

**Comment by iamnoah** [comment]
Cool. If you come up with a general workaround, I'd be happy to incorporate it.
