### ISSUE TITLE
Adsense workaround?

### ISSUE THREAD

**Issue by mostacholoco** [iamnoah/writeCapture#25]
Hi Noah,
First of all, I want to congratulate you for developing such a useful tool. Now, let's go for the question :)

I'm working on a website that is displaying Adsense ads by means of ajax and, of course, I'm using writeCapture to display them. However, I stumbled with the following issue. I can only get 4 ads properly; when I try to get the 5th I get a 400 Bad Request status code.

If I then navigate not using ajax then the counter gets reset. It seems this is a restriction from Adsense and it is pretty annoying. Ideally, I would keep refreshing the ads when the user navigates the site. But as my knowledge of JQuery, JavaScript and even networking is very limited I find it quite difficult to get these stuff solved.

I have some questions in mind which I don't know the answer which seem to be key to solve this issue such as:
 1- How does the server recognizes that there is a difference between the ajax requests and the non-ajax request? A status code?

 2- Once I perform a non-ajax request and the count is reset, what difference has the following ajax request from the original 4?

 3- Based on the previous questions, is there any way to fake a similar behaviour using writeCapture?

Ok, I know these are quite simple (stupid) questions and maybe not very related to writeCapture, but I would appreciate if you could give me a hand with this :)

Thanks in advance,
Mosty

**Comment by iamnoah** [comment]
So loading AdSense in the way you're describing may violate the Google Terms of Use. You could get your account suspended and lose any revenue Google hasn't paid out. Additionally, based on my reading of the obfuscated AdSense code, Google does seem to be taking technical measures to prevent libraries like writeCapture from working, so I can't promise support.

That said, people seem to have luck with iframes: http://webmasters.stackexchange.com/questions/2506/is-it-possible-to-use-asynchronous-google-adsense-i-e-non-blocking
