### ISSUE TITLE
Problems with scripts that do a document.write and access the written elements

### ISSUE THREAD

**Issue by vincejl** [iamnoah/writeCapture#26]
We ran into an issue where an ad was being written with document.write and then tried to access the dom elements written. The writeOnGetElementById option seems to remedy this, but we didn't want to override document.getElementById for performance reasons. What do you guys think of this patch that gives the option to have document.write calls to be written immediately, bypassing the queue?

<pre>
275c275,276
&lt;       writeOnGet = getOption('writeOnGetElementById',options),  

---
>       writeOnGet = getOption('writeOnGetElementById',options),
>       immediate = getOption('immediateWrites', options),
283,284c284,285
&lt;     doc.write = replacementWrite;
&lt;     doc.writeln = replacementWriteln;

---
>     doc.write = immediate ? immediateWrite : replacementWrite;
>     doc.writeln = immediate ? immediateWriteln : replacementWriteln;
301a303,310
>     }
>     function immediateWrite(s) {
>       var target = $.$(context.target);
>       target.parentNode.innerHTML += s;
>     }
>     function immediateWriteln(s) {
>       var target = $.$(context.target);
>       target.parentNode.innerHTML += s + '\n';
</pre>

**Comment by iamnoah** [comment]
I don't see any problems with this. Submit a pull request.

What kind of performance improvements are you seeing?
