### ISSUE TITLE
Having to repeat call to writeCapture twice in order to get ad to render

### ISSUE THREAD

**Issue by jeromecovington** [iamnoah/writeCapture#29]
Hi I'm having to repeat my call to writeCapture in order to get the ad to show up. (Snippet of code below.) If I do not call writeCapture twice, the ad does not show up.

```
function injectDartScript() {
    wrapper.writeCapture().html(script);
    wrapper.writeCapture().html(script);
}

function init() {
    wrapper = $('#dart-site-banner');

    getCookieParams();
    createDartScript();
    injectDartScript();
}
```

**Comment by iamnoah** [comment]
I can't really help you without knowing what 'script' is. A live URL demonstrating the problem would be ideal.

**Comment by jeromecovington** [comment]
Sorry about that, I thought might have been a known issue. I will put a demo together.

## 

Regards,
Jerome

**Comment by iamnoah** [comment]
Please open a new ticket if you can get a working demo.

**Comment by jeromecovington** [comment]
Well it seems to be a result of using Hashsignal JS in conjunction with writeCapture, so a "working" demo has been hard to recreate. Maybe I will have some time for experimentation soon.

## 

Regards,
Jerome
