### ISSUE TITLE
Problem with writeCapture + Pointroll ads

### ISSUE THREAD

**Issue by jeka-org** [iamnoah/writeCapture#30]
Great library, it's the only solution that's even come close to serving all DFP ads properly. Having a problem with one Pointroll ad though - here's a sample page I put up that shows the issue:

http://jeka.co/test/pointroll.php

Looks like everything goes through and even the ad that's supposed to go through gets downloaded but it never shows up and the div ends up being empty. Do you have any idea what the problem may be? Tried all the options, etc. This occurs with both jquery and non-jquery versions.

Funny thing - that pointroll ad worked with my basic homebrew solution (capture document.write into buffer, preg match script tags, execute each) and worked with bezen solution (similar idea, more evolved) but doesn't work with writeCapture - whereas writeCapture is able to handle all the other insane ads that bezen and homebrew failed on. 

Any ideas?

**Comment by iamnoah** [comment]
Looks like the ad is being written into the head element. There is an
untested branch to deal with that:
https://github.com/iamnoah/writeCapture/tree/getElementsByTag

Did you try forceLastScriptTag = true? Probably not, since it's undocumented...

On Thu, Aug 11, 2011 at 2:12 PM, jekadotco
reply@reply.github.com
wrote:

**Comment by iamnoah** [comment]
Gah, ignore the first part, that's something else. You probably just need

writeCapture.forceLastScriptTag = true;

**Comment by jeka-org** [comment]
Thanks for the response! Just tried forceLastScriptTag = true, also tried the different branch - still no go.

**Comment by iamnoah** [comment]
Well, if you look in Firebug, you can see your ad is there in the head element. I'll have to play with it more later.

**Comment by iamnoah** [comment]
So this script is actually quite clever. It detects if the document is loaded and falls back to the DOM. Unfortunately, it's very precise in detecting it's own tag, so the hack doesn't work and it puts everything in the head.

So really you don't need write capture in this case. You can just add the script tag (using the DOM, not innerHTML or jQuery) where you want it and it will do the right thing. 

However, you're probably looking for a general solution where you can always apply writeCapture. So try this code: https://github.com/iamnoah/writeCapture/tree/scriptInPlace

I haven't tested it at all, so if it dies with an error, let me know.

**Comment by jeka-org** [comment]
Noah, you're a bloody genius. That worked 100%. I had to correct a few small things to make it run but BOY does it run!!!

YEAHHH!!!!!!

Thanks a ton, I can't believe it's all working now, I was starting to give up. Crazy.

**Comment by iamnoah** [comment]
Please do some cross browser testing. I'm concerned the approach may have
quirks in different browsers.

**Comment by jeka-org** [comment]
Yep, that's the plan. So far it works in IE7,8,9, FF5. Will do a more thorough run through with a bunch of different ads/browser combinations tomorrow.

**Comment by jeka-org** [comment]
So far so good... the code's now live on 967kissfm.com, kase101.com and 800-ish other Clear Channel radio websites. If something doesn't work, I will know very soon.

**Comment by mikerobinson** [comment]
One additional thing I found out working on this one - Pointroll is -very- picky when it comes to what you're requesting. jQuery, by default, appends a cachebuster to the end of it's requests ("_=[TIMESTAMP]"). If you're doing your own cachebusting with DART via ord=, you actually have to enable jQuery caching so that it doesn't append the _= to the end of your request.

**Comment by jeka-org** [comment]
Yep. I ran into that as well, though I got that one figured out before running into the brick wall which I'd still be stuck at if not for Noah.

Noah for president. Srsly.

**Comment by melwynfurtado** [comment]
I am facing similar problem with one of my DART ad loading outside the container and getting appended to page bottom.
What was the fix suggested?

**Comment by iamnoah** [comment]
@melwynfurtado give [writeCapture2](https://github.com/iamnoah/writeCapture/tree/writeCapture2) a try.

**Comment by iamnoah** [comment]
Hi,

Commenting on somone else's issue is not going to get you any answers. Please ask on the mailing list.

**Comment by melwynfurtado** [comment]
Thanks. Added as a new issue.

**Comment by jeka-org** [comment]
If it helps, this is the version that I ended up using - it may slightly differ from trunk but I _think_ that the changes that Noah ended up helping me with ended up in trunk:

http://www.jeka.co/code/wc/writeCapture.js

I also called it with:
asyncAll: false
writeOnGetElementById: true

Cheers
Jeka
