### ISSUE TITLE
Ads not respecting destination div#id and loading in the wrong place

### ISSUE THREAD

**Issue by azcazandco** [iamnoah/writeCapture#35]
# Summary of issue

I've been attempting to implement your script however no matter which way I try and do so I always seem to get the ads loading in the wrong target id.  Do you have any ideas about where I might be getting things wrong?  This happens no matter whether I do inline scripts or use a document.ready.
## Example

```
<div id="ad-1"></div>
<script language="javascript" type="text/javascript">       
  $('#ad-1').writeCapture().html('<scr'+'ipt type="text/javascript" src="script url"><'+'/script>').end();
</script>   

<div id="ad-2"></div>
<script language="javascript" type="text/javascript">           
  $('#ad-2').writeCapture().html('<scr'+'ipt type="text/javascript" src="script url"><'+'/script>').end();
</script>           

<div id="ad-3"></div> 
<script language="javascript" type="text/javascript">       
  $('#ad-3').writeCapture().html('<scr'+'ipt type="text/javascript" src="script url"><'+'/script>').end();
</script>       
```

Any help with this is appreciated, it looks like I'm getting the exact same results no matter what browser I'm using.

**Comment by iamnoah** [comment]
Write capture expects the page to be loaded. These scripts will block load. Wrap them in $();

**Comment by azcazandco** [comment]
Not sure what you mean by wrap them in $(); can you provide an example?  Do you mean just like this before the closing body tag? :

```
$(function(){
    $('#ad-1').writeCapture().html('<scr'+'ipt type="text/javascript" src="http://"><'+'/script>').end();
    $('#ad-2').writeCapture().html('<scr'+'ipt type="text/javascript" src="http://"><'+'/script>').end();
    $('#ad-3').writeCapture().html('<scr'+'ipt type="text/javascript" src="http://"><'+'/script>').end();
    $('#ad-4').writeCapture().html('<scr'+'ipt type="text/javascript" src="http://"><'+'/script>').end();
});
```

Unfortunately that presents the same issue where they don't load where they're supposed to but I don't know if that's what you mean or not.

**Comment by iamnoah** [comment]
I was saying do this:

```
  $(document).ready(function() {
      $('#ad-1').writeCapture().html('<scr'+'ipt type="text/javascript" src="script url"><'+'/script>');
      $('#ad-2').writeCapture().html('<scr'+'ipt type="text/javascript" src="script url"><'+'/script>');
      $('#ad-3').writeCapture().html('<scr'+'ipt type="text/javascript" src="script url"><'+'/script>');
  });
```

If you still have issues after doing that, please post a link to a jsFiddle demonstrating the issue.
