### ISSUE TITLE
Incompatible with AdSense/DFP?

### ISSUE THREAD

**Issue by slowernet** [iamnoah/writeCapture#36]
I'm unable to get any output when using jquery.writeCapture with Google ad tags. I'm using jquery.writecapture head, Chrome 16, Firefox 7, Safari 5.1 Mac.

Test page with 4 slots (at least two of which should populate) here:
http://ny.eater.com/_por.html?google_debug

I the slots populated with div#__document_write_ajax_div-N, but no callback or replacement is made thereafter. In FF console, I see the message "A call to document.write() from an asynchronously-loaded external script was ignored."

I have tried all permutations of    $.writeCapture.proxyGetElementById and $.writeCapture.writeOnGetElementById.

Let me know if I can supply any other information. Thanks for the time.

**Comment by iamnoah** [comment]
A lot of people seem to have trouble with AdSense. I think they do it on purpose.

It's also a violation of the AdSense terms to dynamically change it. You could get your account frozen.

There is no plan to support AdSense in writeCapture.

**Comment by slowernet** [comment]
Thanks. Might be useful to specifically note this in the wiki.
