### ISSUE TITLE
Using writeCapture to change ads through a gallery

### ISSUE THREAD

**Issue by oweichselbaum** [iamnoah/writeCapture#37]
Hi,

I'm trying to use your writeCapture library, so when I click to the next image my div with the ads refresh, except they also display every ad in the cycle.  

My test js being used in the console:

var innerhtml = jQuery('#sidebar_ad').html();
jQuery('#sidebar_ad').writeCapture().html(innerhtml);

Again, this does refresh the ads, but instead of displaying 2 ads, which is what it's supposed to do, it displays 8 ads, which are all part of that cycle.

The ads can be viewed on the right rail at: http://stage.youbeauty.com/hair/galleries/celebrities-with-black-hair

Except the plugin is not yet on that site, only on my local site.

Any ideas/help would be appreciated.

Thanks,
Oren

**Comment by iamnoah** [comment]
When you make this call:

```
 jQuery('#sidebar_ad').html()
```

You get all the script tags _currently_ in that element. That means you get the script that loaded the ad as well as any scripts it wrote. 

You need to give writeCapture the clean, uninterpreted HTML.
