### ISSUE TITLE
How Do I Install This Plugin?

### ISSUE THREAD

**Issue by NoLimitList** [iamnoah/writeCapture#39]
Hi,

I'm trying to install this plugin, but every test install I do fails to trigger an using the test code from the "Usage" page and I cannot find any installation instructions anywhere. I need this plugin to load my AdBrite ads because putting the code on a lone html document and writing an Iframe to the main page onready causes some ads to break and render partially if not completely below the framed part of the other document in IE 7 &  IE 8 even if I make the frame larger than 728x90 for a leaderboard.

So far I've tried including jQuery, WriteCapture, and the latest jQuery plugin for write capture in various configurations such as:

```
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.4.min.js"></script>
<script type="text/javascript" src="http://mysite.com/js/writeCapture.js"></script>
<script type="text/javascript" src="http://mysite.com/js/jquery.writeCapture-1.0.5-min.js"></script>
<script type="text/javascript" src="http://mysite.com/js/testwritecapture.js"></script>
```

I've also tried:

<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.4.min.js"></script>

```
<script type="text/javascript" src="http://mysite.com/js/jquery.writeCapture-1.0.5-min.js"></script>
<script type="text/javascript" src="http://mysite.com/js/testwritecapture.js"></script>
```

I would go on, but that is basically all I've tried so far and I can't think of any reason why the plugin does not respond at all. In both cases the file testwritecapture.js contains the following code copied from your "Usage" page which should trigger an alert once loaded:

$.writeCapture.autoAsync(function () {
    alert('Ads loaded!'); // don't do this though, it would be annoying
});

I have yet to see a single alert. I must admit that I am a little lost when it comes to JavaScript because I'm primarily a C# programmer who works within the ASP.Net framework, so usually I just have to drag and drop a control before using server side code to do everything I need. I'm only messing with JavaScript because I want ads to load quicker.

**Comment by NoLimitList** [comment]
In addition it appears that $.writeCapture is null or not an object.

**Comment by iamnoah** [comment]
Please do not use the issue tracker for [support](http://catb.org/~esr/faqs/smart-questions.html#forum). If you have questions, try the [mailing list](http://groups.google.com/group/writecapturejs-users).

**Comment by NoLimitList** [comment]
Sorry about that. Could you tell me what I'm doing wrong. I've never had
this much trouble using a jQuery plugin before and your works like exactly
what I've been looking for to run ads. Other options I've tried don't work
in all browsers and in some cases they will even break pages causing them to
render just whitespace or just the ad after the page load.

-----Original Message-----
From: noah
[mailto:reply+i-2039514-ff6507f6bded4469b506e775f57c05dab1c1e91d@reply.githu
b.com] 
Sent: Monday, October 24, 2011 3:54 PM
To: NoLimitList
Subject: Re: [writeCapture] How Do I Install This Plugin? (#39)

Please do not use the issue tracker for
[support](http://catb.org/~esr/faqs/smart-questions.html#forum). If you have
questions, try the [mailing
list](http://groups.google.com/group/writecapturejs-users).

##
