### ISSUE TITLE
Discovered this

### ISSUE THREAD

**Issue by neskire** [iamnoah/writeCapture#4]
Hi iamnoah,

Kudos for the plugin, works really well - but I have one banner that breaks the site - in chrome it simply loads only the specific banner overwriting everything else - in ff it simply stops.

So far I have narrowed it down to this - will investigate further

http://ds.serving-sys.com/BurstingCachedScripts//SBTemplates_3_0_22/StdBanner.js?ai=2585308

**Comment by iamnoah** [comment]
The first issue I've discovered is that a script tag is written that contains neither a type or language attribute. The browser seems to assume that it is JavaScript. So writeCapture needs to process that..

The second is a script tag that does not quote the src attribute. e.g., `<script src=http://foo.com>`, which is allowed as long as the attribute doesn't have whitespace. So the attribute parsing code needs to be changed.

**Comment by iamnoah** [comment]
Changes have been made and the ad seems to work properly now.
