### ISSUE TITLE
Fails with <script foo="bar"src="baz">

### ISSUE THREAD

**Issue by joehoyle** [iamnoah/writeCapture#41]
writeCapture fails if the script has non space before the src attribute. this is probably incorrect behaviour on this publisher's part, but this maybe something writecapture could work around.

I modified attrPattern to

``` JavaScript
    function attrPattern(name) {
        return new RegExp('[\\s\\r\\n]?'+name+'=(?:(["\'])([\\s\\S]*?)\\1|([^\\s>]+))','i');
    }
```

**Comment by iamnoah** [comment]
Can you open a pull request? Thanks.
