### ISSUE TITLE
Two ads on a page causing type error

### ISSUE THREAD

**Issue by cgwin** [iamnoah/writeCapture#42]
Hello,

Thanks for making this super helpful library. I am running into a bit of a weird issue.

When I have two ads on a page and run write capture I am getting a Uncaught TypeError: Object #<Object> has no method '2' and Uncaught TypeError: Object #<Object> has no method '3' with the following stack output

globalEval
reffering to - head.insertBefore( script, head.firstChild );

global.writeCaptureSupport.replaceWith
reffering to - globalEval(scripts[i]);

html
reffering to - $.replaceWith(context.target,sanitize(markup,safeOpts(options),queue,context) + (cb || ''));

captureAndResume
reffering to - html(uncapture(state), 

script.onload.script.onreadystatechange
reffering to - success();

I am using the no-lib library with the tool. I have also tried with the jquery plugin and I am getting the same error. If I switch the order of the ads, the first one will always run and the second one will always fail. If I call the ads by themselves, both will load with writecapture but when both are present only 1 will load. 

The writecapture code is being called like so
function(settings){
    console.log(settings)
    var adsrc = dartAdSettings.createDartTag(settings);
    var adhtml = '<script language="JavaScript" src="'+adsrc+'" type="text/javascript"><\/script>'
    writeCapture.proxyGetElementById = true;
    //writeCapture.writeOnGetElementById = true; I have tried with and without this it makes no difference.
    writeCapture.html("#"+settings["id"],adhtml)
}

Thanks for your help,
CG

**Comment by cgwin** [comment]
Looks like I broke the comment tool 

<pre>
function(settings){
    console.log(settings)
    var adsrc = bimDartAdSettings.bimcreateDartTag(settings);
    writeCapture.fixUrls(adsrc)
    var adhtml = '<script language="JavaScript" src="'+adsrc+'" type="text/javascript"><\/script>'
    writeCapture.proxyGetElementById = true;
    writeCapture.writeOnGetElementById = true;
    writeCapture.html("#"+settings["id"],adhtml)
}
</pre>

**Comment by iamnoah** [comment]
https://github.com/iamnoah/writeCapture (See Help!)

Please create a jsfiddle and send it to the mailing list.
