### ISSUE TITLE
el is undefined when calling the function before currents adds have finished

### ISSUE THREAD

**Issue by hutber** [iamnoah/writeCapture#44]
Hi there.

Just wondering if you've ever come across 'el is undefined' error before? 

The only way i recreate this error is call the function and then calling it again before the adds have finished loading from the first call. 

Heres my code, this code runs each time :
 ajaxAds.changeAds = function (){
      //Remove Current Adds
      $('#banner').empty();

```
  var str_html_banner = tmgAdsBuildAdTag("ban", "728x90,468x60", "adj", "", 2);
  $('#banner').html(writeCapture.sanitize(str_html_banner));
```

}

While i'll write something on my end to wait until everything has loaded i just wondered if there was anything you're aware of that might do this?

Again cheers for making this fully sexy plug-in :)

**Comment by iamnoah** [comment]
Multiple calls should run serially. That may be an error inside the scripts you're loading.

Make sure you're not sanitizing HTML that has already been inserted into the DOM.

If you can create a test case on JS Fiddle, we can debug it better.
