### ISSUE TITLE
Wait to finish before next capture?

### ISSUE THREAD

**Issue by sislamoglu** [iamnoah/writeCapture#45]
Is there anyway to queue captures?

Or let me ask like this:

Is there any possibly way actually make two or more writeCaptures do their job to wait until previous capture finished...

**Comment by sislamoglu** [comment]
Sorry, my bad not noticing { done: func }

You might like to underline it , can easily be missed :)

**Comment by iamnoah** [comment]
There is actually an internal queue in write capture. Even if you make two consecutive calls, the second wont run until the first has finished. However, if a loaded script does something asynchronously, neither the internal queue or the done callback can guarantee that it finishes before the next call.

**Comment by sislamoglu** [comment]
My script configuration was like this:
1. Capture script A (which sets dome document.x variable)
2. if (document.x == ) { call another capture }  else { call yet another capture } 

But variable was not set ofcourse for next line, unless I wait for done function, so it is solved :) 

Thank you greatly for this, for long have I been looking for this :)
