### ISSUE TITLE
Ajax callbacks not firing properly

### ISSUE THREAD

**Issue by aariacarterweir** [iamnoah/writeCapture#46]
When loading ads in, I'm often left with the following trailing text node:
window['**document_write_ajax_callbacks**']['50']();

Any idea of where I could start even looking to hack in a fix?

**Comment by iamnoah** [comment]
That usually means the script that was run had an error, so writeCapture wasn't able to cleanup. You can try enabling the various options writeCapture accepts: https://github.com/iamnoah/writeCapture/wiki/Options

There is also an experimental rewritten version of write capture available here that could be more compatible with your ads:
https://github.com/iamnoah/writeCapture/blob/writeCapture2/writeCapture2.js

**Comment by aariacarterweir** [comment]
Thanks iamnoah - writecapture has been a fantastic product for us. Does the new version have any dependencies? I couldn't get it to work at all. Looks like it might need require.js ?

**Comment by iamnoah** [comment]
Ah sorry, an AMD loader.js is not required (but they are supported). https://github.com/iamnoah/element.write is required though.

**Comment by aariacarterweir** [comment]
Thanks :)

**Comment by aariacarterweir** [comment]
Sorry iamnoah, no luck with this. Any way for me to just kill the text?

**Comment by iamnoah** [comment]
If you're using writeCapture2, there should be no text...

**Comment by aariacarterweir** [comment]
There's the problem then - I couldn't get writeCapture2 to work at all for me - but will give it a spin. Regardless of the text issues - I'm really grateful for the work you've put into this solution. It's a life-saver.

**Comment by ehoch** [comment]
Any luck on fixing this issue or getting writeCapture2 to work?
