### ISSUE TITLE
doXDomainLoad fails to make a network request

### ISSUE THREAD

**Issue by kingcons** [iamnoah/writeCapture#47]
This has been suggested as a slightly ridiculous error case. It's several requests to sanitize a single div (ad rotator) in rapid succession. In response to this mistreatment, writeCapture promptly dies.

To reproduce:
1. Go to http://www.wsbtv.com/gallery/news/10-year-old-mauled-dogs/gGGk/#660698
2. Double click on the next or prev arrows for the gallery or on one of the photos.
3. Ads are not displayed. This is the writecapture call in question: https://github.com/coxmediagroup/marimo/blob/master/lib/marimo.js#L431

**Comment by iamnoah** [comment]
It's generally a really bad idea to make a lot of ad requests like that anyway. It will often get you baned or fined by your ad network. I'd wait 2-3 seconds before invoking writeCapture to ensure the user has stopped clicking.
