### ISSUE TITLE
In safari 5.1 writeCapture dosent work properly

### ISSUE THREAD

**Issue by captainweb9** [iamnoah/writeCapture#48]
Hello,
My code working in almost any browser including IE7,8,9 (forget about IE6).
Js & html code is on same domain still its not working.
Every time it returns me blank div  `<div style='margin:0px;padding:0px;border:none;' id='atm_div_0.6820882398169488'></div>`.
But if I change referrer by developer tool to any other browser then it works perfectly fine.
Can you please tell me whats the problem.

**Comment by iamnoah** [comment]
Did you try writeCapture2? https://github.com/iamnoah/writeCapture/tree/writeCapture2

That markup is generated by your ad script, so it is probably an error in the ad. Please submit a jsfiddle that reproduces the problem to the mailing list.

**Comment by captainweb9** [comment]
Thanks for quick response.
Will try it.

**Comment by captainweb9** [comment]
I can not reopen issue.
http://jsfiddle.net/sZaCF/8/ is my jsfiddle url.
Problem looks consistent in all safaris on windows & linux os.
