### ISSUE TITLE
Problem in safari browsers & problem in working with writeCapture 2 

### ISSUE THREAD

**Issue by captainweb9** [iamnoah/writeCapture#49]
Hello Noah,
I have submitted you https://github.com/iamnoah/writeCapture/issues/48 before, saying writeCapture gives problem while working with safari browsers .Didn't get any reply there after posting my jsfiddel demo , so created new issue.
I have found out that if ad is iframe like survey form etc then it gives problem else if ad is just a banner then it works fine.
You suggested me to use writecapture 2 , but still I am not able to make it work.
I am giving you links of jsfiddel ,
writeCapture 2 demo - http://jsfiddle.net/CBTuC/
writeCature demo which do not work in safari - http://jsfiddle.net/sZaCF/8/

**Comment by iamnoah** [comment]
Your demo does not include write capture or its dependencies. If you need support getting set up, please use the mailing list.
