### ISSUE TITLE
Ad load for specific ad format blocks other successive ads on page.

### ISSUE THREAD

**Issue by melwynfurtado** [iamnoah/writeCapture#50]
Hi Noah,

I am not able to load more than one ad in the page. I have created a fiddle to reproduce what issue I exactly face on my work environment page.

http://jsfiddle.net/dnj53/5/

Am i missing something here? One detail I observed is that this issue occurs when I am trying to load the specific ad fomat(Lady gaga video). It might be due to network latency from the ad publisher network.

Thanks
Melwyn

**Comment by iamnoah** [comment]
Please read the README. Unless you have a specific test case proving the issue is in writeCapture, this is not the forum for asking for help.
