### ISSUE TITLE
writeCapture.proxyGetElementById = true; failing on ie6 and ie7

### ISSUE THREAD

**Issue by mcat** [iamnoah/writeCapture#6]
The offending line seems to be:
var result = state.getEl.call(global.document,id);

It seems that IE host objects are not proper JavaScript objects in ie6 and ie7 and cannot be modified with the .call() method.

The error that IE throws is "Object doesn't support this property or method".

**Comment by iamnoah** [comment]
Fixed. Now we test for the error at startup and don't use call.
