### ISSUE TITLE
Problem with IE 6 and 7

### ISSUE THREAD

**Issue by jasper-ferrer** [iamnoah/writeCapture#7]
The code below works on all major browsers and IE 8, but does not work on IE 6 and 7:

```
    writeCapture.proxyGetElementById = true;
    $("#placeHolder1").html( writeCapture.sanitize(
        "<script type=\"text/javascript\">\n" +
        "document.write(unescape(\'%3Cscript type=\"text/javascript\" src=\"\'+\n" +
        "document.location.protocol+\'//counter.goingup.com/js/tracker.js?st=xdxc7cr&b=5\"%3E%3C/script%3E\'));\n" +
        "</script>\n" ) );
```

The third party Javascript is a GoingUP tag. It creates an A element with id gubadge. On IE 6 and 7, this A element fails to be created.

**Comment by iamnoah** [comment]
Hi Jasper,

Can you add what version of writeCapture you are using?

Thanks

**Comment by jasper-ferrer** [comment]
Noah,

This is the file that I am using:

```
    writeCapture-0.9.0-nolib-min.js
```

I just saw that there is now a 1.0 relase. I'm gonna try that tomorrow then I'll let you know happens.

Thanks.

**Comment by iamnoah** [comment]
Hmmm, from the looks of the script, while it may render in other browsers, it wont work properly. It's setting onmouseover on the created link, which is not something writeCapture currently supports. I suppose we could copy the on- attributes from the proxy element...

**Comment by iamnoah** [comment]
Using the latest code, this appears to work in IE 6 & 7:

```
$('#placeHolder1').writeCapture('html','<script type="text/javascript" src="http://counter.goingup.com/js/tracker.js?st=xdxc7cr&b=5\"> </script>')
```

Although, like I said, the onmouseover callback is certainly not attached.

**Comment by iamnoah** [comment]
I've added some code to try to copy the element attributes if jQuery is available (setting attributes is non-trivial).

**Comment by jasper-ferrer** [comment]
Thank you very much Noah.

Grabbed the latest release (writeCapture-1.0.0-nolib-min.js) and I can confirm that GoingUP tag is now supported by writeCapture.

**Comment by jasper-ferrer** [comment]
Correction, in my last post what I was referring to as the latest release is this: jquery.writeCapture-1.0.0-min.js.

**Comment by iamnoah** [comment]
Thanks!
